services:
   mysql:
      image: mysql:5.7
      command: --default-authentication-plugin=mysql_native_password
      expose:
         - "3306"
      ports:
         - "3306:3306"
      volumes:
         - ./mysql_db:/var/lib/mysql
      environment:
         MYSQL_ROOT_PASSWORD: Tesla1234
         MYSQL_DATABASE: expense-manager-db
